
export const data = [{
    title: "Discrete Math",
    month: "September",
    day: 1,
    year: 2022,
    description: "",
    links: [
        "https://en.wikipedia.org/wiki/Computer_science",
        "https://www.britannica.com/science/computer-science",
        "https://www.cs.ucla.edu/",
    ],
},
{
    title: "(Title) Prof. X started a new project",
    month: "July",
    day: 7,
    year: 2022,
    description:
        "(Brief description) Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore asd Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore asd",
    links: [],
},
{
    title: "AI",
    month: "July",
    day: 7,
    year: 2022,
    description: "This is second example",
    links: [],
},
{
    title: "Graphics Programming",
    month: "December",
    day: 6,
    year: 2022,
    description:
        "Learn from an expert in the field. He will guide you through the basics of creating an image and adding things like shading.",
    links: [],
},
{
    title: "Game Development",
    month: "August",
    day: 12,
    year: 2022,
    description: "Learn how to create a game from scratch using Unity.",
    links: [],
},
{
    title: "Game DevelopmentIV",
    month: "August",
    day: 15,
    year: 2023,
    description: "Learn how to create a game from scratch using Unity.",
    links: [],
},
{
    title: "AI(II)",
    month: "July",
    day: 9,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(III)",
    month: "July",
    day: 10,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(IV)",
    month: "July",
    day: 11,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(V)",
    month: "July",
    day: 12,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(VI)",
    month: "July",
    day: 13,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(VII)",
    month: "July",
    day: 14,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(VIII)",
    month: "July",
    day: 15,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(IX)",
    month: "July",
    day: 16,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(X)",
    month: "July",
    day: 17,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(XI)",
    month: "July",
    day: 9,
    year: 2021,
    description: "This is another example",
    links: [],
},
{
    title: "AI(XII)",
    month: "July",
    day: 9,
    year: 2021,
    description: "This is another example",
    links: [],
},
];
export default data;
