export const projectsMap = [
	{
		id: 1,
		title: "Project #1",
		description:
			"Reiciendis non fuga. Excepturi autem pariatur commodi dolorum quasi labore temporibus optio. Dolore magni explicabo ipsum. Iste ad laborum velit facilis accusamus officiis voluptate veniam.",
		status: "Completed",
		startDate: "6/23/2022",
		endDate: "11/26/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 2,
		title: "Project #2",
		description:
			"Porro praesentium nobis sunt sed molestiae. A eaque omnis assumenda dolore iusto maiores id veniam.",
		status: "Completed",
		startDate: "3/23/2022",
		endDate: "11/28/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 3,
		title: "Project #3",
		description:
			"Eveniet accusamus cupiditate porro temporibus reiciendis placeat blanditiis. Enim voluptatum voluptate deserunt repudiandae.",
		status: "Completed",
		startDate: "8/17/2022",
		endDate: "11/26/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 4,
		title: "Project #4",
		description:
			"Accusamus dolore amet. Nisi laborum aliquid perspiciatis deserunt adipisci inventore praesentium reprehenderit. Quia ut minus deserunt ea officia nisi. Possimus aliquam eaque alias. Nesciunt corporis consequatur iure nam tempore minus animi fugiat et.",
		status: "Completed",
		startDate: "11/24/2021",
		endDate: "11/19/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 5,
		title: "Project #5",
		description:
			"Ducimus facilis laboriosam vitae nobis. Dolorum laboriosam consequuntur soluta reiciendis dolorum nihil.",
		status: "Ongoing",
		startDate: "7/30/2022",
		endDate: "11/28/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 6,
		title: "Project #6",
		description:
			"Voluptatum saepe hic quasi ratione. Quisquam molestias necessitatibus. Aperiam temporibus debitis doloremque pariatur occaecati eius quam quod.",
		status: "Completed",
		startDate: "11/3/2022",
		endDate: "11/27/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 7,
		title: "Project #7",
		description:
			"Rerum aliquam enim animi at nesciunt rerum architecto maxime. Consectetur aliquam blanditiis similique quo distinctio blanditiis eos numquam quas. Blanditiis nesciunt placeat cumque tempora perferendis eius consectetur quaerat.",
		status: "Ongoing",
		startDate: "11/30/2021",
		endDate: "11/19/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 8,
		title: "Project #8",
		description:
			"Excepturi aut temporibus quidem inventore quibusdam architecto eum aspernatur. Libero soluta excepturi natus iusto corporis quasi dolorum. Iure dolores sed molestiae maxime quibusdam. Sed occaecati in odio sit ratione. Commodi in iusto accusamus libero inventore soluta tempora.",
		status: "Completed",
		startDate: "3/30/2022",
		endDate: "11/25/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 9,
		title: "Project #9",
		description:
			"Veniam dolorum voluptatem a cumque rem fugit. Ratione nemo impedit architecto cumque adipisci facere nihil nihil. Officiis quisquam quo veniam. Voluptatem officiis praesentium accusamus aut nesciunt. Esse blanditiis exercitationem assumenda dolore inventore ab molestias ex.",
		status: "Ongoing",
		startDate: "8/15/2022",
		endDate: "11/20/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
	{
		id: 10,
		title: "Project #10",
		description:
			"Aliquid earum voluptatem. Distinctio sed blanditiis excepturi sit minus sapiente exercitationem.",
		status: "Ongoing",
		startDate: "8/10/2022",
		endDate: "11/26/2022",
		discordUrl: "https://discord.com/",
		gitUrl: "https://github.com/",
		projectUrl: "https://angular.io/",
	},
];
